server:
  port: 38801
  servlet:
    context-path: /

spring:
  application:
    name: AplpDocumentService
  cloud:
    nacos:
      discovery:
        server-addr: zixiu.xyz:28801
        namespace: 29de6fd4-24f4-4585-ab94-c43564f4ed1d